### ISSUE TITLE
Poisoned SIG_USART0_RECV

### ISSUE THREAD

**Issue by rgars** [greiman/SerialPort#1]
When recompiling a program that had previously worked successfully with Arduino IDE 1.6.7 with 1.8.3 it pointed to an error arising from Line 213 of SerialPort.cpp:
/Arduino/libraries/SerialPort/SerialPort.cpp:213:15: error: attempt to use poisoned "SIG_USART0_RECV"
 #elif defined(SIG_USART0_RECV)

Searching the forums I have found some references to this error, but no indications about how to overcome it.

Can you help?

**Comment by greiman** [comment]
Looks like some old symbols for interrupt vectors have been "poisoned" recently.

I removed code with the symbols SIG_USART0_RECV, SIG_UART0_RECV, SIG_UART_RECV.

Try the modified version.

Here is the diff:
```
213,220d212
< #elif defined(SIG_USART0_RECV)
< ISR(SIG_USART0_RECV) {
<   rx_isr(0);
< }
< #elif defined(SIG_UART0_RECV)
< ISR(SIG_UART0_RECV) {
<   rx_isr(0);
< }
225,228d216
< #elif defined(SIG_UART_RECV)
< ISR(SIG_UART_RECV) {
<   rx_isr(0);
< }
```

**Comment by rgars** [comment]
Thanks for the quick response.

I have removed those lines from SerialPort.cpp

I now get a different compile error:-

Arduino: 1.8.3 (Mac OS X), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

HardwareSerial0.cpp.o (symbol from plugin): In function `Serial':
(.text+0x0): multiple definition of `__vector_25'
libraries/SerialPort/SerialPort.cpp.o (symbol from plugin):(.text+0x0): first defined here
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.9.2/../../../../avr/bin/ld: Disabling relaxation: it will not work with multiple definitions
HardwareSerial0.cpp.o (symbol from plugin): In function `Serial':
(.text+0x0): multiple definition of `__vector_26'
libraries/SerialPort/SerialPort.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.

I can't find '_vector_26' in SerialPort.cpp. Any ideas?

**Comment by greiman** [comment]
Some part of your sketch or a library is using Serial.  You can't use both SerialPort and  Arduino Serial in your program.  They both require use of interrupt vectors which can't be shared.

Here are definitions for Mega from  arduino-1.8.3/hardware/tools/avr/avr/include/avr/iomxx0_1.h
```
#define USART0_RX_vect			_VECTOR(25)
#define USART0_UDRE_vect		_VECTOR(26)
```

This program will get the same error
```
#include <SerialPort.h>
// use NewSerial for port 0
USE_NEW_SERIAL;

void setup() {
  NewSerial.begin(9600);
  NewSerial.println("Hello World!");
  Serial.print("Cause error");
}
void loop() {}
```


> (.text+0x0): multiple definition of `__vector_25'
> libraries\SerialPort\SerialPort.cpp.o (symbol from plugin):(.text+0x0): first defined here
> d:/arduino/arduino-1.8.3/hardware/tools/avr/bin/../lib/gcc/avr/4.9.2/../../../../avr/bin/ld.exe: Disabling relaxation: it will not work with multiple definitions
> HardwareSerial0.cpp.o (symbol from plugin): In function `Serial':
> (.text+0x0): multiple definition of `__vector_26'
> libraries\SerialPort\SerialPort.cpp.o (symbol from plugin):(.text+0x0): first defined here

**Comment by rgars** [comment]
Thanks again for the quick reply and insight!

The sketch has worked without errors since 2013, but obviously there are other recent changes to libraries, etc.

The libraries I explicitly include are:
`#include <SerialPort.h>
#include <SdFat.h>
#include <Wire.h>
#include <RTClib.h>
#include <Adafruit_BMP085.h>`

In the sketch I set up serial ports 0, 1 & 2
`// Setup serial ports
SerialPort<0, 63, 63> NewPort;
SerialPort<1, 255, 255> NewPort1;     // Serial port buffers 256 bytes for send and receive
SerialPort<2, 255, 255> NewPort2;     // Serial port buffers 256 bytes for send and receive
`
and these are started by the following statements:
` NewPort.begin(115200);
  // connect to the NMEA at the desired rate
  NewPort1.begin(NMEARATE);
  NewPort2.begin(NMEARATE); `

Port 0 is used for output to the  Serial monitor, while ports 1 & 2 are used to send and receive NMEA 0183 data.

Perhaps it is trying to use the SerialPort library to operate Port 0 that is causing the problem.

 If I just use the SerialPort library for ports 1 & 2 [where I need the bigger buffer sizes], should it work with handling Port 0 through the Serial library? Is the Serial library is included by default?

Is there a way to exclude the Serial library if it is included by default? [I note the error messages refer to HardwareSerial - is that a part of Serial?]

I apologise with my lack of knowledge of the details in this area - previously the sketch worked without these problems.

The entire Sketch is attached
[Log_NMEA_sentences_2_06.pdf](https://github.com/greiman/SerialPort/files/1117146/Log_NMEA_sentences_2_06.pdf)

**Comment by greiman** [comment]
I found a problem, initErrorHalt() prints to Serial.

Try replacing this:
`sd.initErrorHalt();`
with:
`sd.initErrorHalt(&NewPort);`

**Comment by rgars** [comment]
Thanks.

I have made that change, but still get the following:-
Arduino: 1.8.3 (Mac OS X), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

HardwareSerial0.cpp.o (symbol from plugin): In function `Serial':
(.text+0x0): multiple definition of `__vector_25'
libraries/SerialPort/SerialPort.cpp.o (symbol from plugin):(.text+0x0): first defined here
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.9.2/../../../../avr/bin/ld: Disabling relaxation: it will not work with multiple definitions
HardwareSerial0.cpp.o (symbol from plugin): In function `Serial':
(.text+0x0): multiple definition of `__vector_26'
libraries/SerialPort/SerialPort.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.


I have also tried changing all the Port0 lines to use Serial rather than SerialPort, but still get the same error messages.

**Comment by rgars** [comment]
I have found a comment in the Arduino forum:-

"Re: Help replacing hardware serial libraries
#11
Nov 08, 2016, 01:30 pm Last Edit: Nov 08, 2016, 02:23 pm by ALKVA
OK, at least part of the mystery is solved.  The file SdFatUtil.h, associated with the SD library, contains obscure functions that call Serial.write() which pulls-in the hardware serial libraries.  SdFile.cpp also has some functions that call Serial.write()."

So maybe the HardwareSerial library is called from the SDFat library. Not sure how to eliminate that library as writing data to an SD card is a major function of the sketch.

**Comment by rgars** [comment]
SdFat.h does have some output to Serial. Not sure whether those can be eliminated. I expect that I'll need to check all the other libraries too.

Might it be possible to go back to the 2013 versions of Arduino IDE and libraries?

**Comment by greiman** [comment]
I extracted your sketch from the pdf file and am able to compile it without errors after this change.

`sd.initErrorHalt(&NewPort);`

I used IDE 1.8.3 and selected Mega 2560.

I used the current version of SdFat and SerialPort located here on github.  I used the latest (several year old) version of Adafruit_BMP085 from github

I used an old version of RTClib.

Here is the result:

> Sketch uses 22796 bytes (8%) of program storage space. Maximum is 253952 bytes.
> Global variables use 2861 bytes (34%) of dynamic memory, leaving 5331 bytes for local variables. Maximum is 8192 bytes.

**Comment by greiman** [comment]
The SdFat calls to Serial are inline in .h files so they are not linked unless you call them from your sketch.

I used the latest Adafruit version of RTClib from github and it is fine.

**Comment by rgars** [comment]
Thanks very much for testing it out.

I'll check that all my libraries are up to date and hopefully get the same outcome!

**Comment by rgars** [comment]
Magic!

Outcome:-

> Archiving built core (caching) in: /var/folders/zk/34q_c0x55672wkhschtv_j6w0000gn/T/arduino_cache_78641/core/core_arduino_avr_mega_cpu_atmega2560_8c285f3eadd391e41dc56bc71478f5da.a
> Sketch uses 22790 bytes (8%) of program storage space. Maximum is 253952 bytes.
> Global variables use 2861 bytes (34%) of dynamic memory, leaving 5331 bytes for local variables. Maximum is 8192 bytes.

Thank you very much for your help!!

I can now get on with the minor improvement I was trying to make when this cropped up!
